spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supper_market
    username: suppermarket
    password: suppermarket
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true