#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/online-shop
#    username: onlineshop
#    password: onlineshop
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

spring:
  kafka:
    bootstrap-servers: 9092
  datasource:
    url: jdbc:mysql://localhost:3306/online-shop
    username: root
    password: 16072002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring-security:
  jwt:
    secret-key: "mothaibabonnamsaubaytamchinmuoiJQKkichtaivithichemnhieuquanenemlainoilaaloianhguivaocaurapchoemdinhcathinhcamoi"
    expiration: 86400000  # one day
    refresh-token: 604800000  # 7 days


# Command to run zookeeper: .\bin\windows\zookeeper-server-start.bat .\config\zookeeper.properties
# Command to run broker: .\bin\windows\kafka-server-start.bat .\config\server.properties
# DB endpoint: db-onlineshop-1.chpfcpdehods.ap-southeast-1.rds.amazonaws.com

