spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online-shop
    username: root
    password: 16072002
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true